name: Build

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
      - name: Install
        run: yarn --no-immutable
      - name: Build
        run: yarn build packages/core
      - name: Examples
        run: |-
          yarn build examples/cross-platform
          yarn build examples/node-classic
          yarn build examples/node-hybrid
          yarn build examples/node-next
          yarn build examples/wildcard
          git diff --exit-code

  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
      - name: Install
        run: yarn --no-immutable
      - name: Lint
        run: yarn lint
